---
apiVersion: v1
kind: Namespace
metadata:
  name: openldap
  labels:
    name: "openldap"
---
apiVersion: v1
kind: Service
metadata:
    name: openldap
    namespace: openldap
    labels:
        app.kubernetes.io/name: openldap
spec:
    type: ClusterIP
    ports:
        - name: tcp-ldap
          port: 1389
          targetPort: tcp-ldap
    selector:
        app.kubernetes.io/name: openldap
---
apiVersion: apps/v1
kind: Deployment
namespace: openldap
metadata:
  labels:
    app: openldap
  name: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
    type: Recreate
  template:
    metadata:
      labels:
        app: openldap
        deploymentconfig: openldap
    spec:
      containers:
      - image: quay.io/feven/openldap
        imagePullPolicy: Always
        name: openldap
        env:
            - name: OPENLDAP_ROOT_DN_SUFFIX
              value: "dc=company,dc=local"
            - name: OPENLDAP_ROOT_PASSWORD
              value: "admin"



