---
apiVersion: v1
kind: Namespace
metadata:
  name: openldap
  labels:
    name: "openldap"
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    name: openldap
spec:
  type: NodePort
  ports:
    - port: 1389
      nodePort: 30389
      name: http
  selector:
    app: openldap
---
apiVersion: apps/v1
kind: Deployment
namespace: openldap
metadata:
  labels:
    app: openldap
  name: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
    type: Recreate
  template:
    metadata:
      labels:
        app: openldap
        deploymentconfig: openldap
    spec:
      containers:
      - image: quay.io/feven/openldap-bitnami
        imagePullPolicy: Always
        name: openldap
        env:
            - name: LDAP_ADMIN_USERNAME
              value: "admin"
            - name: LDAP_ADMIN_PASSWORD
              value: "adminpassword"
            - name: LDAP_USERS
              value: "customeuser"
            - name: LDAP_PASSWORDS
              value: "custompassword"
